### ISSUE TITLE
Can't get the plugin to work / How to add episodes?

### ISSUE THREAD

**Issue by AdrianFahrbach** [mauricerenck/kirby-podcaster#16]
Hey there,

I can't get this plugin to work. I get this whenever I try to open the feed:

> Call to a member function podcasterMatomoFeedEnabled() on null

I guess that's because it doesn't find any episodes? If yes, how do I add them?

My current page setup is:

```
kirby/
├── home/
├── contact/
├── [...]
└── podcast/
   ├── feed
   ├── episode-1
```

My "Source Page" is "podcast". I'm using the podcasterfeed blueprint for the feed page and the following blueprint for my episode site:

```
title: Podcast Episode
tabs:
    podcast:
        extends: tabs/podcasterepisode
```

My mp3 file is uploaded to the "podcasterMp3" field within the episode-1 panel.
